#############################################################################
# Makefile for building: theMplayer
# Generated by qmake (2.01a) (Qt 4.8.2) on: ?? ???. 12 00:12:17 2012
# Project:  theMplayer.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile theMplayer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=i686 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=i686 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lavcodec -lavformat -lavutil -lswscale -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		SetupDialog.cpp \
		TestMovieGrid.cpp \
		MovieGrid.cpp \
		Movie.cpp \
		MovieFile.cpp \
		MovieWidget.cpp \
		ScrollableGrid.cpp \
		Utils.cpp \
		ScrollableGridWithCursor.cpp \
		MovieWidgetFactory.cpp \
		MovieWidget_Movie.cpp \
		MovieWidget_Directory.cpp \
		GridLayout.cpp moc_SetupDialog.cpp \
		moc_MovieGrid.cpp \
		moc_MovieWidget.cpp \
		moc_MovieWidgetFactory.cpp \
		moc_MovieWidget_Movie.cpp \
		moc_MovieWidget_Directory.cpp
OBJECTS       = main.o \
		SetupDialog.o \
		TestMovieGrid.o \
		MovieGrid.o \
		Movie.o \
		MovieFile.o \
		MovieWidget.o \
		ScrollableGrid.o \
		Utils.o \
		ScrollableGridWithCursor.o \
		MovieWidgetFactory.o \
		MovieWidget_Movie.o \
		MovieWidget_Directory.o \
		GridLayout.o \
		moc_SetupDialog.o \
		moc_MovieGrid.o \
		moc_MovieWidget.o \
		moc_MovieWidgetFactory.o \
		moc_MovieWidget_Movie.o \
		moc_MovieWidget_Directory.o
DIST          = /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		theMplayer.pro
QMAKE_TARGET  = theMplayer
DESTDIR       = 
TARGET        = theMplayer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: theMplayer.pro  /usr/share/qt/mkspecs/linux-g++/qmake.conf /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile theMplayer.pro
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/common/gcc-base.conf:
/usr/share/qt/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt/mkspecs/common/g++-base.conf:
/usr/share/qt/mkspecs/common/g++-unix.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile theMplayer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/theMplayer1.0.0 || $(MKDIR) .tmp/theMplayer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/theMplayer1.0.0/ && $(COPY_FILE) --parents SetupDialog.h TestMovieGrid.h main.h MovieGrid.h Movie.h MovieFile.h MovieWidget.h ScrollableGrid.h DrawingDirection.h ScrollingDirection.h Utils.h ScrollableGridWithCursor.h MovieWidgetFactory.h MovieWidget_Movie.h MovieWidget_Directory.h GridLayout.h .tmp/theMplayer1.0.0/ && $(COPY_FILE) --parents main.cpp SetupDialog.cpp TestMovieGrid.cpp MovieGrid.cpp Movie.cpp MovieFile.cpp MovieWidget.cpp ScrollableGrid.cpp Utils.cpp ScrollableGridWithCursor.cpp MovieWidgetFactory.cpp MovieWidget_Movie.cpp MovieWidget_Directory.cpp GridLayout.cpp .tmp/theMplayer1.0.0/ && (cd `dirname .tmp/theMplayer1.0.0` && $(TAR) theMplayer1.0.0.tar theMplayer1.0.0 && $(COMPRESS) theMplayer1.0.0.tar) && $(MOVE) `dirname .tmp/theMplayer1.0.0`/theMplayer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/theMplayer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_SetupDialog.cpp moc_MovieGrid.cpp moc_MovieWidget.cpp moc_MovieWidgetFactory.cpp moc_MovieWidget_Movie.cpp moc_MovieWidget_Directory.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_SetupDialog.cpp moc_MovieGrid.cpp moc_MovieWidget.cpp moc_MovieWidgetFactory.cpp moc_MovieWidget_Movie.cpp moc_MovieWidget_Directory.cpp
moc_SetupDialog.cpp: SetupDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) SetupDialog.h -o moc_SetupDialog.cpp

moc_MovieGrid.cpp: GridLayout.h \
		DrawingDirection.h \
		ScrollableGridWithCursor.h \
		ScrollableGrid.h \
		ScrollingDirection.h \
		MovieGrid.h
	/usr/bin/moc $(DEFINES) $(INCPATH) MovieGrid.h -o moc_MovieGrid.cpp

moc_MovieWidget.cpp: MovieWidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) MovieWidget.h -o moc_MovieWidget.cpp

moc_MovieWidgetFactory.cpp: MovieWidget.h \
		MovieWidgetFactory.h
	/usr/bin/moc $(DEFINES) $(INCPATH) MovieWidgetFactory.h -o moc_MovieWidgetFactory.cpp

moc_MovieWidget_Movie.cpp: Movie.h \
		MovieFile.h \
		MovieWidget.h \
		MovieWidget_Movie.h
	/usr/bin/moc $(DEFINES) $(INCPATH) MovieWidget_Movie.h -o moc_MovieWidget_Movie.cpp

moc_MovieWidget_Directory.cpp: MovieGrid.h \
		GridLayout.h \
		DrawingDirection.h \
		ScrollableGridWithCursor.h \
		ScrollableGrid.h \
		ScrollingDirection.h \
		MovieWidget.h \
		MovieWidget_Directory.h
	/usr/bin/moc $(DEFINES) $(INCPATH) MovieWidget_Directory.h -o moc_MovieWidget_Directory.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp DrawingDirection.h \
		main.h \
		MovieGrid.h \
		GridLayout.h \
		ScrollableGridWithCursor.h \
		ScrollableGrid.h \
		ScrollingDirection.h \
		SetupDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

SetupDialog.o: SetupDialog.cpp main.h \
		SetupDialog.h \
		TestMovieGrid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SetupDialog.o SetupDialog.cpp

TestMovieGrid.o: TestMovieGrid.cpp TestMovieGrid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TestMovieGrid.o TestMovieGrid.cpp

MovieGrid.o: MovieGrid.cpp MovieWidgetFactory.h \
		MovieWidget.h \
		MovieWidget_Directory.h \
		MovieGrid.h \
		GridLayout.h \
		DrawingDirection.h \
		ScrollableGridWithCursor.h \
		ScrollableGrid.h \
		ScrollingDirection.h \
		MovieWidget_Movie.h \
		Movie.h \
		MovieFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MovieGrid.o MovieGrid.cpp

Movie.o: Movie.cpp Movie.h \
		MovieFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Movie.o Movie.cpp

MovieFile.o: MovieFile.cpp MovieFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MovieFile.o MovieFile.cpp

MovieWidget.o: MovieWidget.cpp MovieWidget.h \
		Utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MovieWidget.o MovieWidget.cpp

ScrollableGrid.o: ScrollableGrid.cpp ScrollableGrid.h \
		DrawingDirection.h \
		ScrollingDirection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScrollableGrid.o ScrollableGrid.cpp

Utils.o: Utils.cpp Utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Utils.o Utils.cpp

ScrollableGridWithCursor.o: ScrollableGridWithCursor.cpp ScrollableGridWithCursor.h \
		ScrollableGrid.h \
		DrawingDirection.h \
		ScrollingDirection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScrollableGridWithCursor.o ScrollableGridWithCursor.cpp

MovieWidgetFactory.o: MovieWidgetFactory.cpp MovieWidgetFactory.h \
		MovieWidget.h \
		Movie.h \
		MovieFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MovieWidgetFactory.o MovieWidgetFactory.cpp

MovieWidget_Movie.o: MovieWidget_Movie.cpp MovieWidget_Movie.h \
		Movie.h \
		MovieFile.h \
		MovieWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MovieWidget_Movie.o MovieWidget_Movie.cpp

MovieWidget_Directory.o: MovieWidget_Directory.cpp MovieWidget_Directory.h \
		MovieGrid.h \
		GridLayout.h \
		DrawingDirection.h \
		ScrollableGridWithCursor.h \
		ScrollableGrid.h \
		ScrollingDirection.h \
		MovieWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MovieWidget_Directory.o MovieWidget_Directory.cpp

GridLayout.o: GridLayout.cpp GridLayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GridLayout.o GridLayout.cpp

moc_SetupDialog.o: moc_SetupDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SetupDialog.o moc_SetupDialog.cpp

moc_MovieGrid.o: moc_MovieGrid.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MovieGrid.o moc_MovieGrid.cpp

moc_MovieWidget.o: moc_MovieWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MovieWidget.o moc_MovieWidget.cpp

moc_MovieWidgetFactory.o: moc_MovieWidgetFactory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MovieWidgetFactory.o moc_MovieWidgetFactory.cpp

moc_MovieWidget_Movie.o: moc_MovieWidget_Movie.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MovieWidget_Movie.o moc_MovieWidget_Movie.cpp

moc_MovieWidget_Directory.o: moc_MovieWidget_Directory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MovieWidget_Directory.o moc_MovieWidget_Directory.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

